project:
  type: website
  output-dir: docs

website:
  title: "Math 3190 Portfolio"
  
  sidebar:
    style: "docked"
    contents:
      - section: "Homework"
        contents:
              - href: Homework/Homework_1.html
              - href: Homework/Homework_2.html
              - href: Homework/Homework_3.html
              - href: Homework/Homework_4.html
              - href: Homework/Homework_5.html
              - href: Homework/Homework_6.html
              - href: Homework/Homework_7.html
              - href: Homework/Homework_8.html
              - href: Homework/Homework_9.html
              - href: Homework/Homework_10.html

    right:
      - icon: github
        href: https://github.com/YOUR_USERNAME


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

