project:
  type: website
  output-dir: docs

website:
  title: "Math 3190 Portfolio"

  navbar:
    left:
      - text: Home
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/RMMcMurray/Math-3190-Projects

  sidebar:
    style: "docked"
    contents:
      - section: "Homework"
        contents:
          - Homework/Homework_1.html
          - Homework/Homework_2.html
          - Homework/Homework_3.html
          - Homework/Homework_4.html
          - Homework/Homework_5.html
          - Homework/Homework_6.html
          - Homework/Homework_7.html
          - Homework/Homework_8.html
          - Homework/Homework_9.html
          - Homework/Homework_10.html

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true